//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuxPrecios
    {
        public Nullable<int> Id { get; set; }
        public int Marca { get; set; }
        public Nullable<int> Modelo { get; set; }
        public int Tamanio { get; set; }
        public Nullable<int> Tipo { get; set; }
        public int CantidadPack { get; set; }
        public decimal Costo { get; set; }
        public decimal Porcentaje { get; set; }
        public decimal PrecioVenta { get; set; }
    }
}
