//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuxPrecios
    {
        public int Marca { get; set; }
        public int Tamanio { get; set; }
        public decimal Costo { get; set; }
        public decimal Porcentaje { get; set; }
        public decimal PrecioVenta { get; set; }
        public int Modelo { get; set; }
    }
}
