//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_pedido
    {
        public int det_id { get; set; }
        public int det_pedido { get; set; }
        public int det_producto { get; set; }
        public int det_cantidad { get; set; }
        public decimal det_precio { get; set; }
        public decimal det_monto { get; set; }
    
        public virtual producto producto { get; set; }
    }
}
