//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class gasto
    {
        public int gas_id { get; set; }
        public System.DateTime gas_fecha { get; set; }
        public string gas_descripcion { get; set; }
        public decimal gas_monto { get; set; }
    }
}
