//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class gasto
    {
        public int gas_id { get; set; }
        public System.DateTime gas_fecha { get; set; }
        public string gas_descripcion { get; set; }
        public decimal gas_monto { get; set; }
    }
}
