//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BD_Entities : DbContext
    {
        public BD_Entities()
            : base("name=BD_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AuxPrecios> AuxPrecios { get; set; }
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<envase> envase { get; set; }
        public virtual DbSet<gasto> gasto { get; set; }
        public virtual DbSet<grupo> grupo { get; set; }
        public virtual DbSet<localidad> localidad { get; set; }
        public virtual DbSet<marca> marca { get; set; }
        public virtual DbSet<modelo> modelo { get; set; }
        public virtual DbSet<pedido> pedido { get; set; }
        public virtual DbSet<pedido_detalle> pedido_detalle { get; set; }
        public virtual DbSet<precio> precio { get; set; }
        public virtual DbSet<precio_detalle> precio_detalle { get; set; }
        public virtual DbSet<producto> producto { get; set; }
        public virtual DbSet<provincia> provincia { get; set; }
        public virtual DbSet<remito> remito { get; set; }
        public virtual DbSet<rendicion> rendicion { get; set; }
        public virtual DbSet<tamanio> tamanio { get; set; }
        public virtual DbSet<tipo> tipo { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<rendicion_detalle> rendicion_detalle { get; set; }
    }
}
