//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class precio_detalle
    {
        public int prd_campre { get; set; }
        public int prd_produ { get; set; }
        public decimal prd_precioC { get; set; }
        public decimal prd_porcen { get; set; }
        public decimal prd_precioPV { get; set; }
    
        public virtual precio precio { get; set; }
        public virtual producto producto { get; set; }
    }
}
