//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTO()
        {
            this.DETALLE_PEDIDO = new HashSet<DETALLE_PEDIDO>();
        }
    
        public int prod_id { get; set; }
        public int prod_marca { get; set; }
        public int prod_modelo { get; set; }
        public int prod_tamanio { get; set; }
        public int prod_tipo { get; set; }
        public decimal prod_precio_unitario { get; set; }
        public decimal prod_precio_pack { get; set; }
        public int prod_cant_pack { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_PEDIDO> DETALLE_PEDIDO { get; set; }
        public virtual MARCA MARCA { get; set; }
        public virtual MODELO MODELO { get; set; }
        public virtual TAMANIO TAMANIO { get; set; }
        public virtual TIPO TIPO { get; set; }
    }
}
