//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class rendicion
    {
        public int ren_id { get; set; }
        public System.DateTime ren_desde { get; set; }
        public System.DateTime ren_hasta { get; set; }
        public decimal ren_total { get; set; }
    }
}
