//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public string usu_usuario { get; set; }
        public string usu_password { get; set; }
        public byte usu_grupo { get; set; }
        public string usu_nombre { get; set; }
        public string usu_apellido { get; set; }
        public Nullable<System.DateTime> usu_fecha_acceso { get; set; }
    
        public virtual grupo grupo { get; set; }
    }
}
